---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
---

Welcome to Kaiqian's research project: susie-np.

## Project summary

Here is the [project summary](susie-np-summary-20190422.html). 

## Related material

* SuSiE introduction: [SuSiE home](https://stephenslab.github.io/susieR/), [SuSiE paper](https://www.biorxiv.org/content/10.1101/501114v1), [SuSiE repo](https://github.com/stephenslab/susieR)

* SuSiE vignette: [Trend filtering](https://stephenslab.github.io/susieR/articles/trend_filtering.html)

* SuSiE derivation: [SuSiE for trend filtering part](https://www.overleaf.com/read/szdbkckdcbqq)

* DSC simulations: [DSC tutorial](https://stephenslab.github.io/dsc-wiki/overview), [dsc-smooth-gaussian repo](https://github.com/stephenslab/dsc-smooth-gaussian)

* Trend filtering papers:

    + [L1 Trend Filtering](https://web.stanford.edu/~boyd/papers/pdf/l1_trend_filter.pdf)
  
    + [Ten Lecture of Wavelets](https://jqichina.files.wordpress.com/2012/02/ten-lectures-of-waveletsefbc88e5b08fe6b3a2e58d81e8aeb2efbc891.pdf)
  
    + [Adaptive Piecewise Polynomial Estimation via Trend Filtering](http://www.stat.cmu.edu/~ryantibs/papers/trendfilter.pdf)

* Wavelets papers:

    + [A Theory for Multiresolution Signal Decomposition:
The Wavelet Representation ](https://www.di.ens.fr/~mallat/papiers/MallatTheory89.pdf)

    + [Translation-Invariant De-Noising](https://web.stanford.edu/dept/statistics/cgi-bin/donoho/wp-content/uploads/2018/08/TIDeNoise.pdf)
  
    + [Flexible signal denoising via flexible empirical Bayes shrinkage](https://arxiv.org/abs/1605.07787)
  
    + [Wavelet regression and additive models for
irregularly spaced data](https://papers.nips.cc/paper/8112-wavelet-regression-and-additive-models-for-irregularly-spaced-data.pdf)

    + [Wavelet Estimators in Nonparametric Regression: A
Comparative Simulation Study](http://www.mas.ucy.ac.cy/~fanis/Papers/jssv06i06.pdf)

    + [Ideal Spatial Adaptation by Wavelet Shrinkage](http://statweb.stanford.edu/~imj/WEBLIST/1994/isaws.pdf)

## Detailed analyses 

* Please click on [wavelet-susie-20190114](UDWT.html) to see my results.

* Please click on [wavelet-susie-20190117](wavelet-susie-20190117.html) to see my results.

* Please click on [wavelet-susie-20190121](wavelet-susie-20190121.html) to see my results.

* Please click on [wavelet-susie-20190127](wavelet-susie-20190127.html) to see my results.

* Please click on [wavelet-susie-20190129](wavelet-susie-20190129.html) to see my results.

* Please click on [wavelet-susie-20190130](wavelet-susie-20190130.html) to see my results.

* Please click on [v-methods-comparison-dsc-20190213](v_methods_comparison_dsc_20190213.html) to see my results.

* Please click on [v-methods-comparison-debug-20190214](v_methods_comparison_debug_20190214.html) to see my results.

* Please click on [wavelet-susie-20190215](wavelet-susie-20190215.html) to see my results.

* Please click on [wavelet-susie-20190217](wavelet-susie-20190217.html) to see my results.

* Please click on [wavelet-susie-20190221](wavelet-susie-20190221.html) to see my results.

* Please click on [wavelet-susie-20190222](wavelet-susie-20190222.html) to see my results.

* Please click on [wavelet-susie-20190222-2](wavelet-susie-20190222-2.html) to see my results.

* Please click on [wavelet-susie-20190223](wavelet-susie-20190223.html) to see my results.

* Please click on [wavelet-susie-20190228-examples](wavelet-susie-20190228.html) to see my results.

* Please click on [wavelet-susie-20190228-2-examples](wavelet-susie-20190228-2.html) to see my results.

* Please click on [susie-a-20190305](susie-a-20190305.html) to see my results.

* Please click on [susie-a-20190307](susie-a-20190307.html) to see my results.

* Please click on [estimate_residual_variance problem in SuSiE?](susie-a-20190309.html) to see my results.

* Please click on [susie-a-20190310](susie-a-20190310.html) to see my results.

* Please click on [susie-residual-20190313](susie-residual-20190313.html) to see my results.

* Please click on [susie-residual-20190315](susie-residual-20190315.html) to see my results.

* Please click on [susie-symlet-20190319](susie-symlet-20190319.html) to see my results.

* Please click on [susie-symlet-20190327](susie-symlet-20190327.html) to see my results.

* Please click on [DSC analysis: susie versus smashr](dsc-susie-smashr-20190403.html) to see my results.

* Please click on [susie-tf-MAD-20190411](susie-tf-MAD-20190411.html) to see my results.

* Please click on [susie-tf-MAD-20190416](susie-tf-MAD-20190416.html) to see my results.

* Please click on [susie-tf-MAD-20190429](susie-tf-MAD-20190429.html) to see my results.



