---
title: "susie-a-20190307"
author: "Kaiqian Zhang"
date: "3/7/2019"
header-includes:
   - \usepackage{amsmath}
output: 
  workflowr::wflow_html:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(devtools)
install("/Users/Kaiqian /Desktop/susie-aaa")
library(susieR)
```

```{r, include=FALSE}
library(wavethresh)
library(binhf) #Package for shift function
```

## Example 1: minimal example from vignette

I also print `a` for each iteration with and without expanding the parameter. 
```{r}
set.seed(1)
n    <- 1000
p    <- 1000
beta <- rep(0,p)
beta[c(1,2,300,400)] <- 1
X   <- matrix(rnorm(n*p),nrow=n,ncol=p)
y   <- X %*% beta + rnorm(n)
res <- susie(X,y,L=10)
plot(coef(res),pch = 20)
```


```{r}
res <- susie(X,y,L=10, expand_parameter = TRUE)
plot(coef(res),pch = 20)
```

## Example from wavelets

New interpolation scheme:
```{r}
#' @param x is an n-vector of data
#' @return R an n by K interpolation matrix
create_interpolation_matrix = function(x){
  n = length(x)
  #m = 10% * abs(x_i - x_{i+1})
  m = as.numeric(ceiling(1/quantile(sort(abs(diff(x))),0.1)))
  K = 2^(ceiling(log2(m)))
  R = matrix(0, n, K)
  for (i in 1:n){
    for (j in 1:K){
      if (j == 1 & x[i] <= 1/K){
        R[i,j] = 1
      } else if (j == floor(K*x[i]) & x[i] > 1/K & x[i] <=1){
        R[i,j] = (j+1) - K*x[i]
      } else if (j == ceiling(K*x[i]) & x[i] > 1/K & x[i] <=1){
        R[i,j] = K*x[i] - (j-1)
      } else R[i,j] = 0
    }
  }
  return(R)
}
```

```{r}
#' @param K is the dimension of decinmated W
#' @return a K by K matrix, which the transpose of decimated Harr wavelet transform matrix 
create_Wt_DWT = function(K){
  return(GenW(n=K, filter.number=1, family="DaubExPhase"))
}
```

```{r}
create_y = function(x, beta.function, n, sd){
  set.seed(1)
  return(beta.function(x) + rnorm(n, sd=sd))
}
```

```{r}
create_gaps_x = function(n){
  set.seed(1)
  x = sort(runif(n, 0, 1))
  cutidx1 = which(x>0.2 & x<0.3)
  cutidx2 = which(x>0.6 & x<0.8)
  x.cut = x[-c(cutidx1, cutidx2)]
  set.seed(1)
  x.add1 = runif(length(cutidx1), 0.8, 0.9)
  x.add2 = runif(length(cutidx2), 0.3, 0.4)
  x.res = sort(c(x.cut, x.add1, x.add2))
}
```

simulation
```{r}
f.beta4 = function(x){
  n = length(x)
  beta = numeric(n)
  for (i in 1:n){
    if (x[i] < 0.6){
      beta[i] = -3
    } else if(x[i] >= 0.6 & x[i] < 0.65){ 
    } else if(x[i] >= 0.65 & x[i] < 0.7){
      beta[i] = 0
    } else {
      beta[i] = 2
    }
  }
  return(beta)
}
```

```{r}
sd = 0.1
n = 100
set.seed(1)
x = sort(runif(n, 0, 1))
y = create_y(x, beta.function=f.beta4, n, sd)
m = as.numeric(ceiling(1/quantile(sort(abs(diff(x))),0.1)))
K = 2^(ceiling(log2(m)))
```

```{r}
#Create RWt
R = create_interpolation_matrix(x)
Wt.DWT = create_Wt_DWT(K)
RWt = R %*% Wt.DWT
#Run SuSiE
s = susie(RWt, y, L=50, estimate_prior_variance = TRUE, estimate_prior_method = 'optim')
```

```{r}
s.a = susie(RWt, y, L=50, estimate_prior_variance = TRUE, estimate_prior_method = 'optim', expand_parameter = TRUE)
```


```{r}
plot(x, y, pch=20, col="grey", main = "Figure 1")
lines(x, f.beta4(x), col="black", lwd=2)
lines(x, predict(s), col="red", lwd=2)
lines(x, predict(s.a), col="blue", lwd=2)
```


```{r}
sd = 0.1
n = 100
set.seed(1)
x = create_gaps_x(n)
y = create_y(x, beta.function=f.beta4, n, sd)
m = as.numeric(ceiling(1/quantile(sort(abs(diff(x))),0.1)))
K = 2^(ceiling(log2(m)))
```

```{r}
#Create RWt
R = create_interpolation_matrix(x)
Wt.DWT = create_Wt_DWT(K)
RWt = R %*% Wt.DWT
#Run SuSiE
s = susie(RWt, y, L=50, estimate_prior_variance = TRUE, estimate_prior_method = 'optim')
```


```{r}
s.a = susie(RWt, y, L=50, estimate_prior_variance = TRUE, estimate_prior_method = 'optim', expand_parameter = TRUE)
```


```{r}
plot(x, y, pch=20, col="grey", main = "Figure 2: example with two large gaps in xs")
lines(x, f.beta4(x), col="black", lwd=2)
lines(x, predict(s), col="red", lwd=2)
lines(x, predict(s.a), col="blue", lwd=2)
```

```{r}
f.beta5 = function(x){
  n = length(x)
  beta = numeric(n)
  for (i in 1:n){
    if (x[i] < 0.1){
      beta[i] = -3
    } else if(x[i] >= 0.1 & x[i] < 0.6){
      beta[i] = 5
    } else if(x[i] >= 0.6 & x[i] < 0.7){
      beta[i] = -1
    } else if(x[i] >= 0.7 & x[i] < 0.9){
      beta[i] = 3
    }else{
      beta[i] = -3
    }
  }
  return(beta)
}
```

```{r}
sd = 0.1
n = 100
set.seed(1)
x = sort(runif(n, 0, 1))
y = create_y(x, beta.function=f.beta5, n, sd)
m = as.numeric(ceiling(1/quantile(sort(abs(diff(x))),0.1)))
K = 2^(ceiling(log2(m)))
```

```{r}
#Create RWt
R = create_interpolation_matrix(x)
Wt.DWT = create_Wt_DWT(K)
RWt = R %*% Wt.DWT
#Run SuSiE
s = susie(RWt, y, L=50, estimate_prior_variance = TRUE, estimate_prior_method = 'optim')
```

```{r}
s.a = susie(RWt, y, L=50, estimate_prior_variance = TRUE, estimate_prior_method = 'optim', expand_parameter = TRUE)
```

```{r}
plot(x, y, pch=20, col="grey", main = "Figure 3: fit for simulation example 4")
lines(x, f.beta5(x), col="black", lwd=2)
lines(x, predict(s), col="red", lwd=2)
lines(x, predict(s.a), col="blue", lwd=2)
```




