---
title: "susie-symlet-20190327"
author: "Kaiqian Zhang"
date: "3/27/2019"
header-includes:
   - \usepackage{amsmath}
output: 
  workflowr::wflow_html:
    code_folding: hide
---


In this vignette, we plot basis functions for Haar and Symlet.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(susieR)
library(wavethresh)
library(binhf) #Package for shift function
library(smashr)
```

```{r}
#' @param x is an n-vector of data
#' @return R an n by K interpolation matrix
create_interpolation_matrix = function(x){
  n = length(x)
  #m = 10% * abs(x_i - x_{i+1})
  m = as.numeric(ceiling(1/quantile(sort(abs(diff(x))),0.1)))
  K = 2^(ceiling(log2(m)))
  R = matrix(0, n, K)
  for (i in 1:n){
    for (j in 1:K){
      if (j == 1 & x[i] <= 1/K){
        R[i,j] = 1
      } else if (j == floor(K*x[i]) & x[i] > 1/K & x[i] <=1){
        R[i,j] = (j+1) - K*x[i]
      } else if (j == ceiling(K*x[i]) & x[i] > 1/K & x[i] <=1){
        R[i,j] = K*x[i] - (j-1)
      } else R[i,j] = 0
    }
  }
  return(R)
}

#' @param K is the dimension of decinmated W
#' @return a K by K matrix, which the transpose of decimated Harr wavelet transform matrix 
create_Wt_DWT = function(K, type){
  if (type=="Haar"){
    return(GenW(n=K, filter.number=1, family="DaubExPhase"))
  } else if (type=="Symlet"){
    return(GenW(n=K, filter.number=10, family="DaubLeAsymm", bc="periodic"))
  }else{
    stop("Input type should be either Haar or Symlet.")
  }
}

create_y = function(x, beta.function, n, sd, boundaries, beta_vals){
  set.seed(1)
  return(beta.function(x, boundaries, beta_vals) + rnorm(n, sd=sd))
}
```

```{r}
n = 8
x = seq(n)/n
```

```{r}
m = as.numeric(ceiling(1/quantile(sort(abs(diff(x))),0.1)))
K = 2^(ceiling(log2(m)))
#Create RWt
R = create_interpolation_matrix(x)
Wt.symlet = create_Wt_DWT(K, "Symlet")
Wt.haar = create_Wt_DWT(K, "Haar")

```

```{r}
op <- par(mfrow = c(2,4))
for (i in 1:8){
  sfuni <- stepfun(1:7, Wt.haar[,i], f=0)
  plot(sfuni, col=i, lwd=2, main="Haar wavelts")
}
```



```{r}
op <- par(mfrow = c(2,4))
for (i in 1:8){
  sfuni <- stepfun(1:7, Wt.symlet[,i], f=0)
  plot(sfuni, col=i, lwd=2, main="Symlet wavelts_10")
}
```






















